/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  IsOptional,
  IsDate,
  ValidateNested,
  IsEnum,
} from "class-validator";
import { Type } from "class-transformer";
import { GroupWhereUniqueInput } from "../../group/base/GroupWhereUniqueInput";
import { EnumNoteServerity } from "./EnumNoteServerity";
import { EnumNoteStatus } from "./EnumNoteStatus";
@InputType()
class NoteUpdateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  desc?: string;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  dueDate?: Date | null;

  @ApiProperty({
    required: false,
    type: () => GroupWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => GroupWhereUniqueInput)
  @IsOptional()
  @Field(() => GroupWhereUniqueInput, {
    nullable: true,
  })
  group?: GroupWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    enum: EnumNoteServerity,
    isArray: true,
  })
  @IsEnum(EnumNoteServerity, {
    each: true,
  })
  @IsOptional()
  @Field(() => [EnumNoteServerity], {
    nullable: true,
  })
  serverity?: Array<"Low" | "Medium" | "High">;

  @ApiProperty({
    required: false,
    enum: EnumNoteStatus,
  })
  @IsEnum(EnumNoteStatus)
  @IsOptional()
  @Field(() => EnumNoteStatus, {
    nullable: true,
  })
  status?: "ToDo" | "InProgress" | "Done";

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  title?: string;
}
export { NoteUpdateInput };
