/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ObjectType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsDate,
  IsString,
  IsOptional,
  ValidateNested,
  IsEnum,
} from "class-validator";
import { Type } from "class-transformer";
import { Group } from "../../group/base/Group";
import { EnumNoteServerity } from "./EnumNoteServerity";
import { EnumNoteStatus } from "./EnumNoteStatus";
@ObjectType()
class Note {
  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  createdAt!: Date;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  desc!: string;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  dueDate!: Date | null;

  @ApiProperty({
    required: false,
    type: () => Group,
  })
  @ValidateNested()
  @Type(() => Group)
  @IsOptional()
  group?: Group | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  id!: string;

  @ApiProperty({
    required: true,
    enum: EnumNoteServerity,
  })
  @IsEnum(EnumNoteServerity)
  @Field(() => EnumNoteServerity, {
    nullable: true,
  })
  serverity?: "Low" | "Medium" | "High";

  @ApiProperty({
    required: true,
    enum: EnumNoteStatus,
  })
  @IsEnum(EnumNoteStatus)
  @Field(() => EnumNoteStatus, {
    nullable: true,
  })
  status?: "ToDo" | "InProgress" | "Done";

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  title!: string;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  updatedAt!: Date;
}
export { Note };
