/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  IsOptional,
  IsDate,
  ValidateNested,
  IsEnum,
} from "class-validator";
import { Type } from "class-transformer";
import { NoteWhereUniqueInput } from "./NoteWhereUniqueInput";
import { NoteUpdateManyWithoutNotesInput } from "./NoteUpdateManyWithoutNotesInput";
import { UserUpdateManyWithoutNotesInput } from "./UserUpdateManyWithoutNotesInput";
import { EnumNoteSeverity } from "./EnumNoteSeverity";
@InputType()
class NoteUpdateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  desc?: string;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  dueDate?: Date | null;

  @ApiProperty({
    required: false,
    type: () => NoteWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => NoteWhereUniqueInput)
  @IsOptional()
  @Field(() => NoteWhereUniqueInput, {
    nullable: true,
  })
  note?: NoteWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => NoteUpdateManyWithoutNotesInput,
  })
  @ValidateNested()
  @Type(() => NoteUpdateManyWithoutNotesInput)
  @IsOptional()
  @Field(() => NoteUpdateManyWithoutNotesInput, {
    nullable: true,
  })
  notes?: NoteUpdateManyWithoutNotesInput;

  @ApiProperty({
    required: false,
    type: () => UserUpdateManyWithoutNotesInput,
  })
  @ValidateNested()
  @Type(() => UserUpdateManyWithoutNotesInput)
  @IsOptional()
  @Field(() => UserUpdateManyWithoutNotesInput, {
    nullable: true,
  })
  owner?: UserUpdateManyWithoutNotesInput;

  @ApiProperty({
    required: false,
    enum: EnumNoteSeverity,
  })
  @IsEnum(EnumNoteSeverity)
  @IsOptional()
  @Field(() => EnumNoteSeverity, {
    nullable: true,
  })
  severity?: "Low" | "Moderate" | "High" | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  title?: string;
}
export { NoteUpdateInput };
